### ISSUE TITLE
(self-signed) SSL Certificate not accepted

### ISSUE THREAD

**Issue by zhongfu** [tapchat/tapchat#11] opened 2013-01-15 03:28 UTC
When connecting to a network with a self-signed SSL certificate and SSL enabled, the connection fails with the error `SELF_SIGNED_CERT_IN_CHAIN` even though the CA that was used to sign the certificate was trusted on both the phone and the server hosting the tapchat server.

From the log (tapchat running with -v):

```
2013-01-15T03:08:33.640Z - error: TLS auth error: SELF_SIGNED_CERT_IN_CHAIN
2013-01-15T03:08:33.641Z - error: Net error [IotaIRC]: SELF_SIGNED_CERT_IN_CHAIN undefined
```

**Comment by codebutler** [comment] 2013-05-27 22:53
Does it work if you add `SELF_SIGNED_CERT_IN_CHAIN` to the array in irc.js on line 547?

**Comment by grinco** [comment] 2013-12-05 15:42
No, it doesn't. It says:
2013-12-05T15:40:32.557Z - debug: Connection got "error" event Error: DEPTH_ZERO_SELF_SIGNED_CERT
2013-12-05T15:40:32.578Z - error: Net error [Red Hat]: Error: DEPTH_ZERO_SELF_SIGNED_CERT Error: DEPTH_ZERO_SELF_SIGNED_CERT

However my issue is a bit different, ind it could help if I used a CA to sign it and trust it on the server.

**Comment by larsks** [comment] 2014-01-12 01:51
I just purchased and immediately refunded tapchat because of this issue -- I'm trying to connect to an existing irc bouncer that's using a self-signed certificate, and was unable to find an option either on the phone or on the command line to permit self-signed certificates.

**Comment by bobobo1618** [comment] 2014-02-03 07:30
+1 for this. @codebutler any updates?

**Comment by cwc** [comment] 2014-02-03 21:05
I also get the `DEPTH_ZERO_SELF_SIGNED_CERT` error. The problem appears to be due to `tls.connect()` throwing an exception when connecting to a server using a self-signed cert, which in turn causes [the wrong error-handling block](https://github.com/codebutler/tapchat/blob/589f75719adb2a7703fc59546bed960fa5a0156f/lib/irc/irc.js#L609-L613) to be invoked. The [intended logic](https://github.com/codebutler/tapchat/blob/589f75719adb2a7703fc59546bed960fa5a0156f/lib/irc/irc.js#L547-L561) for handling self-signed certs is never reached.

**Comment by bobobo1618** [comment] 2014-02-03 21:06
I actually checked this out last night. It can be fixed by using a
different version of node-IRC (there's a pull request on the node-irc repo)
and patching the client code in tapchat to selfSigned: true.

**Comment by codebutler** [comment] 2014-02-05 07:54
Hi everyone, this should be fixed in the latest commit. It's not released to the NPM server yet but you can install using:

```
$ npm install -g https://github.com/codebutler/tapchat.git
```

Please make sure you have version **0.10.25** of nodejs before installing or testing anything:

```
$ node --version
v0.10.25
```

You can access the web interface by visiting `https://your_tapchat_server:8067`.

You'll need the beta version of the Android app to use the non-release TapChat server. To get it:
1. Join the G+ community https://plus.google.com/communities/114324036729579908612
2. Join the Android beta: https://play.google.com/apps/testing/com.tapchatapp.android
3. Open the Play Store on your device and you'll see an update.

Please let me know if this works, thanks!

**Comment by bobobo1618** [comment] 2014-02-06 05:05
When I started server in foreground + verbose mode, I still had self signed cert issues and when I attempted to connect with the android app, I got the following error from the console:

```
TypeError: Object #<User> has no method 'getBacklog'
    at /home/lucas/node_modules/tapchat/src/tapchat/engine.coffee:183:8
    at callbacks (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:164:37)
    at restrict (/home/lucas/node_modules/tapchat/src/tapchat/engine.coffee:99:15)
    at callbacks (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:164:37)
    at param (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/lucas/node_modules/tapchat/node_modules/express/lib/router/index.js:33:10)
    at next (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.handle (/home/lucas/node_modules/tapchat/node_modules/gzippo/lib/compress.js:137:5)
    at next (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at resume (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/connect/lib/middleware/static.js:65:7)
    at SendStream.error (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/connect/lib/middleware/static.js:80:37)
    at SendStream.EventEmitter.emit (events.js:95:17)  
    at SendStream.error (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/send/lib/send.js:147:51)  
    at SendStream.onStatError (/home/lucas/node_modules/tapchat/node_modules/express/node_modules/send/lib/send.js:248:48)
    at /home/lucas/node_modules/tapchat/node_modules/express/node_modules/send/lib/send.js:320:26  
    at Object.oncomplete (fs.js:107:15)
```

The android app reports an ambiguous Java.lang exception with a ton of random binary output.

Android reports version 2.6.1 as being installed.

**Comment by codebutler** [comment] 2014-02-06 06:57
oops, I totally messed this up. Please try again...

**Comment by bobobo1618** [comment] 2014-02-06 07:11
Okay, now it works fine but the client dies after the first connection to a server. Restarting it works fine.

**Comment by codebutler** [comment] 2014-02-09 01:07
Good to hear, thanks for testing!

If you can reliably reproduce the client crash please open a new ticket.

**Closed as completed by codebutler** 2014-02-09 01:07 UTC

**Comment by tildelowengrimm** [comment] 2014-02-23 06:01
I had the same issue. I'm running Node v0.10.25, but when I try to install from Github, I get a whole load of no fun:

```
user@server:~$ sudo npm install -g https://github.com/codebutler/tapchat.git
npm http GET https://github.com/codebutler/tapchat.git
npm http 200 https://github.com/codebutler/tapchat.git
npm ERR! not a package /root/tmp/npm-408-1uTB1Jy_/1393135091153-0.026243567699566483/tmp.tgz
npm ERR! Error: ENOENT, open '/root/tmp/npm-408-1uTB1Jy_/1393135091153-0.026243567699566483/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "https://github.com/codebutler/tapchat.git"
npm ERR! cwd /home/user
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /root/tmp/npm-408-1uTB1Jy_/1393135091153-0.026243567699566483/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/npm-debug.log
npm ERR! not ok code 0
```

How _should_ I be installing a version that can deal with self-signed certs?

**Comment by bobobo1618** [comment] 2014-02-23 06:05
You need to change https to git+https I believe.

**Comment by tildelowengrimm** [comment] 2014-02-23 06:45
Thanks. That allowed me to install the package, but it doesn't seem to resolve the problem. Tapchat reports version 0.0.41. When I try to connect to a server with a self-signed cert in the chain, I get:

```
2014-02-23T06:17:58.859Z - error: TLS auth error: SELF_SIGNED_CERT_IN_CHAIN
2014-02-23T06:17:58.877Z - error: Net error [OFTC]: SELF_SIGNED_CERT_IN_CHAIN undefined
```
